name: test workflow
on:
  push:
    paths:
    - 'switch_ip.py'

jobs:
  build:
    name: Test switch ip script
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: run
      run: python3 switch_ip.py
    
